#!/usr/bin/env python
import click

from arxiv_chaos.core import get_key_phrases


@click.command()
@click.argument("query")
def cli(query: str):
    click.echo("Querying: " + query)
    phrases = get_key_phrases(query)
    click.echo("Key phrases:")
    for p in phrases:
        click.echo(f'{p.score}\t"{p.phrase}"')


if __name__ == "__main__":
    cli()
